# Generated by Django 4.1.4 on 2024-01-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
